import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Banner from "../components/Banner";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`max-w-7xl mx-auto ${inter.className}`}>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );
}
